<template>
  <div style="display: flex; flex-direction: column">
    <iframe
      src="https://api-starevaluator.com/micro-combo/12?mode=clair"
      frameborder="0"
      data-style-id="widget-micro-combo"
      scrolling="no"
    ></iframe>

    <iframe
      src="https://api-starevaluator.com/micro-button/1?mode=clair"
      frameborder="0"
      width="100%"
      scrolling="no"
    ></iframe>
    <iframe
      src="https://api-starevaluator.com/micro-starscore/1?mode=clair"
      frameborder="0"
      width="100%"
      scrolling="no"
    ></iframe>
    <iframe
      src="https://api-starevaluator.com/mini/1?mode=clair"
      frameborder="0"
      width="100%"
      scrolling="no"
    ></iframe>
    <iframe
      src="https://api-starevaluator.com/starter/1?mode=clair"
      frameborder="0"
      width="100%"
      scrolling="no"
    ></iframe>
    <iframe
      src="https://api-starevaluator.com/micro-combo/1?mode=clair"
      frameborder="0"
      width="100%"
      scrolling="no"
    ></iframe>
    <iframe
      src="https://api-starevaluator.com/micro-star/1?mode=clair"
      frameborder="0"
      width="100%"
      scrolling="no"
    ></iframe>
    <iframe
      src="https://api-starevaluator.com/horizontal/1?mode=clair"
      frameborder="0"
      width="100%"
      scrolling="no"
    ></iframe>
    <iframe
      src="https://api-starevaluator.com/micro-review-count/1?mode=clair"
      frameborder="0"
      width="100%"
      scrolling="no"
    ></iframe>
  </div>
</template>
<script setup lang="ts"></script>
